baseurl: https://nan.rbind.io
title: nan
theme: hugo-theme-console
languageCode: en-us
params:
  animateStyle: animated zoomIn fast
  navlinks:
    - name: about/
      url: /about/
    - name: posts/
      url: /posts/
    - name: projects/
      url: /projects/
  titleCutting: yes

social:
  facebook = "seriousconservation"
  instagram = "seriousconservation"
  twitter = "seriouswildlife"

markup:
  goldmark:
    renderer:
      unsafe: true

googleAnalytics: G-WDTYEYNJZR

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date
  
  params.twitterCard:
    generate: true
    card: "summary"
    image: "https://19mvmv3yn2qc2bdb912o1t2n-wpengine.netdna-ssl.com/science/files/2018/08/tnc_51859534_preview-1260x708.jpg"
    imageAlt: "Default Twitter Card Image"
    site: "seriouswildlife"
    creator: "seriouswildlife"
    title: "nan nourn"
    description: "Your site description."
